workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "./App/AnimeApp.xcworkspace" # Isikan nama project Anda.
        XCODE_SCHEME: "AnimeApp" # Isikan nama scheme project Anda.
    scripts:
      - name: Build debug app
        script: |
         xcode-project build-ipa \
          --workspace "$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - codetronclan@gmail.com # Isikan email untuk notifikasi status building.
