workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "./App/AnimeApp.xcodeproj" # Isikan nama project Anda.
        XCODE_SCHEME: "AnimeApp" # Isikan nama scheme project Anda.
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - codetronclan@gmail.com # Isikan email untuk notifikasi status building.
