workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "App/AnimeApp.xcworkspace" # Isikan nama project Anda.
        XCODE_SCHEME: "AnimeApp" # Isikan nama scheme project Anda.
    scripts:
      - name: Install pods
        script: |
          pod install --repo-update --project-directory=App/
      - name: Build debug app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - codetronclan@gmail.com # Isikan email untuk notifikasi status building.
