platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!:linkage => :static
workspace 'AnimeApp'

pod 'SwiftLint'

def view_pods
  pod 'SDWebImage'
  pod 'RxSwift'
end

def local_pods
  pod 'RealmSwift', '~>10'
end

def network_pods
  pod 'Alamofire'
end

target 'AnimeApp' do
  project './AnimeApp'
end

target 'Core' do
  project '../Core/Core'
end

target 'About' do
  project '../About/About'
end

target 'Shared' do
  project '../Shared/Shared'
end

target 'Home' do
  project '../Home/Home'
  view_pods
  network_pods
end

abstract_target 'Locale' do
  local_pods
  target 'Favorite' do
    project '../Favorite/Favorite'
    view_pods
  end

  target 'Detail' do
    project '../Detail/Detail'
    view_pods
    network_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
